modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/crispytwig/Hearth-and-Home/issues"

[[mods]]
modId = "hnh"
version = "${version}"
displayName = "Hearth & Home"
#updateJSONURL="http://myurl.me/"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/hearth-and-home"
logoFile = "icon.png"
#credits="Thanks for this example mod goes to Java"
authors = "crispytwig"
description = '''
Decorative blocks out of scope to Another Furniture
'''

[[dependencies.hnh]]
modId = "forge"
mandatory = true
versionRange = "[43.1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hnh]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
